/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.dfki.cos.basys.processcontrol.model;
@org.apache.avro.specific.AvroGenerated
public enum ExecutionMode implements org.apache.avro.generic.GenericEnumSymbol<ExecutionMode> {
  AUTO, SEMIAUTO, MANUAL, SIMULATE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ExecutionMode\",\"namespace\":\"de.dfki.cos.basys.processcontrol.model\",\"symbols\":[\"AUTO\",\"SEMIAUTO\",\"MANUAL\",\"SIMULATE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
