/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.dfki.cos.basys.processcontrol.model;
@org.apache.avro.specific.AvroGenerated
public enum HandEventType implements org.apache.avro.generic.GenericEnumSymbol<HandEventType> {
  LEADING_INTO_DIRECTION, LOCATION_REACHED, GRASPED_AT_LOCATION  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"HandEventType\",\"namespace\":\"de.dfki.cos.basys.processcontrol.model\",\"symbols\":[\"LEADING_INTO_DIRECTION\",\"LOCATION_REACHED\",\"GRASPED_AT_LOCATION\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
