/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.dfki.cos.basys.processcontrol.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class HandEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2631835580881070231L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HandEvent\",\"namespace\":\"de.dfki.cos.basys.processcontrol.model\",\"fields\":[{\"name\":\"handName\",\"type\":{\"type\":\"enum\",\"name\":\"HandName\",\"symbols\":[\"LEFT\",\"RIGHT\"]}},{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"HandEventType\",\"symbols\":[\"LEADING_INTO_DIRECTION\",\"LOCATION_REACHED\",\"GRASPED_AT_LOCATION\"]}},{\"name\":\"target\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<HandEvent> ENCODER =
      new BinaryMessageEncoder<HandEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<HandEvent> DECODER =
      new BinaryMessageDecoder<HandEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<HandEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<HandEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<HandEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<HandEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this HandEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a HandEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a HandEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static HandEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private de.dfki.cos.basys.processcontrol.model.HandName handName;
  private de.dfki.cos.basys.processcontrol.model.HandEventType type;
  private java.lang.String target;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public HandEvent() {}

  /**
   * All-args constructor.
   * @param handName The new value for handName
   * @param type The new value for type
   * @param target The new value for target
   */
  public HandEvent(de.dfki.cos.basys.processcontrol.model.HandName handName, de.dfki.cos.basys.processcontrol.model.HandEventType type, java.lang.String target) {
    this.handName = handName;
    this.type = type;
    this.target = target;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return handName;
    case 1: return type;
    case 2: return target;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: handName = (de.dfki.cos.basys.processcontrol.model.HandName)value$; break;
    case 1: type = (de.dfki.cos.basys.processcontrol.model.HandEventType)value$; break;
    case 2: target = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'handName' field.
   * @return The value of the 'handName' field.
   */
  public de.dfki.cos.basys.processcontrol.model.HandName getHandName() {
    return handName;
  }


  /**
   * Sets the value of the 'handName' field.
   * @param value the value to set.
   */
  public void setHandName(de.dfki.cos.basys.processcontrol.model.HandName value) {
    this.handName = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public de.dfki.cos.basys.processcontrol.model.HandEventType getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(de.dfki.cos.basys.processcontrol.model.HandEventType value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'target' field.
   * @return The value of the 'target' field.
   */
  public java.lang.String getTarget() {
    return target;
  }


  /**
   * Sets the value of the 'target' field.
   * @param value the value to set.
   */
  public void setTarget(java.lang.String value) {
    this.target = value;
  }

  /**
   * Creates a new HandEvent RecordBuilder.
   * @return A new HandEvent RecordBuilder
   */
  public static de.dfki.cos.basys.processcontrol.model.HandEvent.Builder newBuilder() {
    return new de.dfki.cos.basys.processcontrol.model.HandEvent.Builder();
  }

  /**
   * Creates a new HandEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new HandEvent RecordBuilder
   */
  public static de.dfki.cos.basys.processcontrol.model.HandEvent.Builder newBuilder(de.dfki.cos.basys.processcontrol.model.HandEvent.Builder other) {
    if (other == null) {
      return new de.dfki.cos.basys.processcontrol.model.HandEvent.Builder();
    } else {
      return new de.dfki.cos.basys.processcontrol.model.HandEvent.Builder(other);
    }
  }

  /**
   * Creates a new HandEvent RecordBuilder by copying an existing HandEvent instance.
   * @param other The existing instance to copy.
   * @return A new HandEvent RecordBuilder
   */
  public static de.dfki.cos.basys.processcontrol.model.HandEvent.Builder newBuilder(de.dfki.cos.basys.processcontrol.model.HandEvent other) {
    if (other == null) {
      return new de.dfki.cos.basys.processcontrol.model.HandEvent.Builder();
    } else {
      return new de.dfki.cos.basys.processcontrol.model.HandEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for HandEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HandEvent>
    implements org.apache.avro.data.RecordBuilder<HandEvent> {

    private de.dfki.cos.basys.processcontrol.model.HandName handName;
    private de.dfki.cos.basys.processcontrol.model.HandEventType type;
    private java.lang.String target;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(de.dfki.cos.basys.processcontrol.model.HandEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.handName)) {
        this.handName = data().deepCopy(fields()[0].schema(), other.handName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.target)) {
        this.target = data().deepCopy(fields()[2].schema(), other.target);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing HandEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(de.dfki.cos.basys.processcontrol.model.HandEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.handName)) {
        this.handName = data().deepCopy(fields()[0].schema(), other.handName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.target)) {
        this.target = data().deepCopy(fields()[2].schema(), other.target);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'handName' field.
      * @return The value.
      */
    public de.dfki.cos.basys.processcontrol.model.HandName getHandName() {
      return handName;
    }


    /**
      * Sets the value of the 'handName' field.
      * @param value The value of 'handName'.
      * @return This builder.
      */
    public de.dfki.cos.basys.processcontrol.model.HandEvent.Builder setHandName(de.dfki.cos.basys.processcontrol.model.HandName value) {
      validate(fields()[0], value);
      this.handName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'handName' field has been set.
      * @return True if the 'handName' field has been set, false otherwise.
      */
    public boolean hasHandName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'handName' field.
      * @return This builder.
      */
    public de.dfki.cos.basys.processcontrol.model.HandEvent.Builder clearHandName() {
      handName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public de.dfki.cos.basys.processcontrol.model.HandEventType getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public de.dfki.cos.basys.processcontrol.model.HandEvent.Builder setType(de.dfki.cos.basys.processcontrol.model.HandEventType value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public de.dfki.cos.basys.processcontrol.model.HandEvent.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'target' field.
      * @return The value.
      */
    public java.lang.String getTarget() {
      return target;
    }


    /**
      * Sets the value of the 'target' field.
      * @param value The value of 'target'.
      * @return This builder.
      */
    public de.dfki.cos.basys.processcontrol.model.HandEvent.Builder setTarget(java.lang.String value) {
      validate(fields()[2], value);
      this.target = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'target' field has been set.
      * @return True if the 'target' field has been set, false otherwise.
      */
    public boolean hasTarget() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'target' field.
      * @return This builder.
      */
    public de.dfki.cos.basys.processcontrol.model.HandEvent.Builder clearTarget() {
      target = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public HandEvent build() {
      try {
        HandEvent record = new HandEvent();
        record.handName = fieldSetFlags()[0] ? this.handName : (de.dfki.cos.basys.processcontrol.model.HandName) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (de.dfki.cos.basys.processcontrol.model.HandEventType) defaultValue(fields()[1]);
        record.target = fieldSetFlags()[2] ? this.target : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<HandEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<HandEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<HandEvent>
    READER$ = (org.apache.avro.io.DatumReader<HandEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.handName.ordinal());

    out.writeEnum(this.type.ordinal());

    out.writeString(this.target);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.handName = de.dfki.cos.basys.processcontrol.model.HandName.values()[in.readEnum()];

      this.type = de.dfki.cos.basys.processcontrol.model.HandEventType.values()[in.readEnum()];

      this.target = in.readString();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.handName = de.dfki.cos.basys.processcontrol.model.HandName.values()[in.readEnum()];
          break;

        case 1:
          this.type = de.dfki.cos.basys.processcontrol.model.HandEventType.values()[in.readEnum()];
          break;

        case 2:
          this.target = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










