/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.dfki.cos.basys.processcontrol.model;
@org.apache.avro.specific.AvroGenerated
public enum HandName implements org.apache.avro.generic.GenericEnumSymbol<HandName> {
  LEFT, RIGHT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"HandName\",\"namespace\":\"de.dfki.cos.basys.processcontrol.model\",\"symbols\":[\"LEFT\",\"RIGHT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
