/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.dfki.cos.basys.processcontrol.model;
@org.apache.avro.specific.AvroGenerated
public enum OccupationCommand implements org.apache.avro.generic.GenericEnumSymbol<OccupationCommand> {
  FREE, OCCUPY, PRIO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OccupationCommand\",\"namespace\":\"de.dfki.cos.basys.processcontrol.model\",\"symbols\":[\"FREE\",\"OCCUPY\",\"PRIO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
