/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.dfki.cos.basys.processcontrol.model;
@org.apache.avro.specific.AvroGenerated
public enum VariableType implements org.apache.avro.generic.GenericEnumSymbol<VariableType> {
  NULL, BOOLEAN, INTEGER, STRING, DOUBLE, DATE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"VariableType\",\"namespace\":\"de.dfki.cos.basys.processcontrol.model\",\"symbols\":[\"NULL\",\"BOOLEAN\",\"INTEGER\",\"STRING\",\"DOUBLE\",\"DATE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
