/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.dfki.cos.basys.platform.spring.kafkamessagingtest.model;

@org.apache.avro.specific.AvroGenerated
public interface TestMessages {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"TestMessages\",\"namespace\":\"de.dfki.cos.basys.platform.spring.kafkamessagingtest.model\",\"types\":[{\"type\":\"record\",\"name\":\"TestMessage\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"}]}],\"messages\":{}}");

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends TestMessages {
    public static final org.apache.avro.Protocol PROTOCOL = de.dfki.cos.basys.platform.spring.kafkamessagingtest.model.TestMessages.PROTOCOL;
  }
}